import copy
import itertools
import numpy as np
from collections import defaultdict
from torch.utils.data import Sampler

from fastreid.utils import comm

def reorder_index(batch_indices, world_size):
    r"""Reorder indices of samples to align with DataParallel training.
    In this order, each process will contain all images for one ID, triplet loss
    can be computed within each process, and BatchNorm will get a stable result.
    Args:
        batch_indices: A batched indices generated by sampler
        world_size: number of process
    Returns:

    """
    mini_batchsize = len(batch_indices) // world_size
    reorder_indices = []
    for i in range(0, mini_batchsize):
        for j in range(0, world_size):
            reorder_indices.append(batch_indices[i + j * mini_batchsize])
    return reorder_indices

class CrossViewIdentitySampler(Sampler):
    """
    Cross-view identity sampler (DDP-safe).

    For each batch:
      - Randomly sample P identities
      - For each identity, sample K instances:
          K/2 from aerial, K/2 from ground
    """

    def __init__(self, data_source, mini_batch_size, num_instances, seed=None):
        self.data_source = data_source
        self.num_instances = num_instances
        self.num_pids_per_batch = mini_batch_size // num_instances

        # DDP info
        self.rank = comm.get_rank()
        self.world_size = comm.get_world_size()
        self.batch_size = mini_batch_size * self.world_size

        # index: pid -> view -> indices
        self.pid_view_index = defaultdict(lambda: defaultdict(list))

        for index, (_, pid, _, view_id, _) in enumerate(self.data_source):
            self.pid_view_index[pid][view_id].append(index)

        self.pids = sorted(self.pid_view_index.keys())

        if seed is None:
            seed = comm.shared_random_seed()
        self.seed = int(seed)

    def __iter__(self):
        start = self.rank
        yield from itertools.islice(
            self._infinite_indices(), start, None, self.world_size
        )

    def _infinite_indices(self):
        np.random.seed(self.seed)

        while True:
            avl_pids = copy.deepcopy(self.pids)
            batch_indices = []

            while len(avl_pids) >= self.num_pids_per_batch:
                selected_pids = np.random.choice(
                    avl_pids, self.num_pids_per_batch, replace=False
                ).tolist()

                for pid in selected_pids:
                    idxs = self._sample_indices_for_pid(pid)
                    batch_indices.extend(idxs)

                if len(batch_indices) == self.batch_size:
                    yield from reorder_index(batch_indices, self.world_size)
                    batch_indices = []

                for pid in selected_pids:
                    avl_pids.remove(pid)

    def _sample_indices_for_pid(self, pid):
        """Sample K indices for one pid: K/2 aerial + K/2 ground."""
        view_dict = self.pid_view_index[pid]
        k = self.num_instances
        k_half = k // 2

        aerial = view_dict.get('Aerial', [])
        ground = view_dict.get('Ground', [])

        idxs = []

        if len(aerial) > 0 and len(ground) > 0:
            idxs_a = np.random.choice(
                aerial, size=k_half, replace=len(aerial) < k_half
            ).tolist()
            idxs_g = np.random.choice(
                ground, size=k_half, replace=len(ground) < k_half
            ).tolist()
            idxs = idxs_a + idxs_g
        else:
            # fallback: only one view available
            all_idxs = aerial + ground
            idxs = np.random.choice(
                all_idxs, size=k, replace=True
            ).tolist()

        np.random.shuffle(idxs)
        return idxs

    # def __len__(self):
    #     return len(self.pids) * self.num_instances
